# .github/workflows/docker-build-push.yml
name: SWE-frontend

# main 브랜치에 push 이벤트가 발생했을 때 실행
on:
  push:
    branches: ['main']

jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub이 제공하는 가상 머신
    steps:
      # 1. 코드를 체크아웃
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인 (Secrets 사용)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: . # Dockerfile 위치
          push: true # 빌드 후 푸시
          tags: ${{ secrets.DOCKER_USERNAME }}/swe-frontend:latest # 이미지 태그
